fix: binary pydantic
building pydantic pulls in maturin-1.10.0, running into a toolchain
incompat

error: failed to parse lock file at:
Caused by:
lock file version 4 requires `-Znext-lockfile-bump`

Signed-off-by: Peter Sabaini <peter.sabaini@canonical.com>